language: python

python:
    - "2.7"

sudo: false

env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-djangomaster

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-djangomaster

addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install tox virtualenv

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
