language: python

python:
    - "2.7"

sudo: false

env:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-dj110

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-dj18
      - env: TOX_ENV=py27-dj19
      - env: TOX_ENV=py27-dj110

install:
    - pip install tox virtualenv

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
