language: python

python:
    - "2.7"

sudo: false

env:
    - TOX_ENV=py27-dj13
    - TOX_ENV=py27-dj14
    - TOX_ENV=py27-dj15
    - TOX_ENV=py27-dj16
    - TOX_ENV=py27-dj17
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-dj110
    - TOX_ENV=py27-djangomaster

matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-dj13
      - env: TOX_ENV=py27-djangomaster

addons:
  apt:
    packages:
    - xmlsec1

install:
    - pip install tox virtualenv

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
